[package]
name = "acropalypse_scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.3"
clap = { version = "4.2.1", features = ["derive"] }

[profile.release]
lto = true
